### ISSUE TITLE
Dependency "FasterXML jackson-databind 2.11.1" contains a number of CVEs

### ISSUE THREAD

**Issue by dougbarbin** [OctopusDeploy/Octopus-TeamCity#173]
[CVE Details](https://www.cvedetails.com/vulnerability-list/vendor_id-15866/product_id-42991/Fasterxml-Jackson-databind.html)

FasterXML jackson-databind is a dependency in the Octopus-Teamcity plugin, and it contains several CVEs of varying severity, as indicated in the link above. I am using Octopus-TeamCity plugin version 6.2.0-robe-test-gha.95 which is using jackson-databind-2.11.1. I believe the stable version (6.1.14) of the plugin Octopus-TeamCity also uses this dependency.

The jackson-databind dependency should be updated to the latest stable version, to improve security of the Octopus-TeamCity plugin.

**Comment by donnybell** [comment]
Resolved in the `6.1.15` release via [this PR](https://github.com/OctopusDeploy/Octopus-TeamCity/pull/174/files).
