### ISSUE TITLE
Latest Teamcity docker image breaks Octo build actions

### ISSUE THREAD

**Issue by garethbudden** [OctopusDeploy/Octopus-TeamCity#41]
We run Linux build agents by using the provided [teamcity docker image](https://hub.docker.com/r/jetbrains/teamcity-agent/), all was working well until we updated to the latest release, 2019.2.
This has caused octopus build steps to fail because jetbrains updated the [dockerfile](https://github.com/JetBrains/teamcity-docker-agent/blob/master/ubuntu/Dockerfile#L20) to run on dotnet 3.0 rather than 2.2.  This meant that octo.exe no longer works as it has a requirement on 2.2 - we have a work around (keep using the older image!) but it would be good to update the plugin when [octo.exe supports dotnet 3.0](https://github.com/OctopusDeploy/OctopusCLI/issues/28)

**Comment by michaelnoonan** [comment]
Hi @garethbudden this should be fixed in 6.0.0 which is shipping today. Embarrassingly, we forgot to ship this back in December. 🤦

**Comment by michaelnoonan** [comment]
Release Note: Upgraded the TeamCity integration to use the `netcore3.1` version of the Octopus CLI (`octo`)
