### ISSUE TITLE
Question: Build information support for GitFlow and other nested branch history

### ISSUE THREAD

**Issue by AlexEngblom** [OctopusDeploy/Octopus-TeamCity#44]
Wondering if we are doing something wrong here, but is it so that the step picks only direct commits in the branch for Octopus build information.

When creating Hotfix from Master, pushing couple commits and merging back to Master, this works ok.

But when we are creating Release branch from Develop and then merging it to Master, we don't get any information from previous branches and end up with a very short build information containing only the merge commit. In example:
5b9c3ab - Merge branch 'release/1.15.0'

Looks to me there's not much to do in the build step configurations for this, so my guess is we have to implement pushing build information to Octopus ourselves.

**Comment by matt-richardson** [comment]
Hi @AlexEngblom - thanks for getting in touch!
We dont often monitor this repo for issues - your best bet is to get in touch with our [support team](https://octopus.com/support) who can make sure the right people see this.
